export const ApiRoutes = {
    API_BASE: '/api',
    HEALTH: '/health',
    AUTH: '/auth',
    USERS: '/users',
    USERID: '/:userId',
    SEND_MAIL: '/send-mail',
    SEND_OTP: '/send-otp',
    VERIFY_OTP: '/verify-otp',
    LOGIN: '/login',
    REFRESH_TOKEN: '/refresh-token',
    DOWNLOAD_FILE: '/download-file',
    DOWNLOAD_EXCEL: '/download-excel',
    OCR: '/ocr',
};
